apiVersion: v1
kind: Secret
metadata:
  name: airport-secrets
type: Opaque
data:
  # echo -n ${} | base64
  JWT_SECRET: TFRmN0JpbG0tZ2lPSHBKRnlpP1Vna0doQ3RWZ0k5aG8wN0VxWm5HcmE/QkNidWwzTkNMV0s0cEZvN3FLcUlKVE8xUVUvbkotRGtoQ2RtQmF2WWg9LUpadklqa3ZVUyFLcENFZW05Mi9NOHVNPXdkRk1tPTg2b0ppVDFMUS9qWnhsTTg4cU9GWUVCZHRxeXNRV2ZKN1ktbWNWQlktWk9kMER5NlMwWDliOHY/M0Q5amJEWGVJVVpGND1MV0FIMW1CalR1IUpkL0Z6cXdmVXZxQVN5S00wWDZlelk/TWV2dW9ycEJEIXhuV1UzODc3Qk9McD9kP29XejBpb1RKMD9iPw==
